//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auctions.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class account
    {
        public account()
        {
            this.buy = new HashSet<buy>();
            this.comment = new HashSet<comment>();
            this.favorite = new HashSet<favorite>();
            this.sell = new HashSet<sell>();
            this.role = new HashSet<role>();
        }
    
        public int idAccount { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        [Required(ErrorMessage = "Podaj hasło!", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string password { get; set; }
        [Required(ErrorMessage = "Podaj nick!", AllowEmptyStrings = false)]
        public string nick { get; set; }
        public string icon { get; set; }
        public Nullable<sbyte> promo { get; set; }
        public string age { get; set; }
    
        public virtual ban ban { get; set; }
        public virtual ICollection<buy> buy { get; set; }
        public virtual ICollection<comment> comment { get; set; }
        public virtual ICollection<favorite> favorite { get; set; }
        public virtual ICollection<sell> sell { get; set; }
        public virtual ICollection<role> role { get; set; }
    }
}
