//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod Ÿród³owy zosta³ wygenerowany na podstawie szablonu.
//
//    Rêczne modyfikacje tego pliku mog¹ spowodowaæ nieoczekiwane zachowanie aplikacji.
//    Rêczne modyfikacje tego pliku zostan¹ zast¹pione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auctions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ban
    {
        public int account_idAccount { get; set; }
        public string date { get; set; }
        public string date_end { get; set; }
        public string content { get; set; }
    
        public virtual account account { get; set; }
    }
}
