//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod Ÿród³owy zosta³ wygenerowany na podstawie szablonu.
//
//    Rêczne modyfikacje tego pliku mog¹ spowodowaæ nieoczekiwane zachowanie aplikacji.
//    Rêczne modyfikacje tego pliku zostan¹ zast¹pione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auctions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.item = new HashSet<item>();
        }
    
        public int idcategory { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<item> item { get; set; }
    }
}
