//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auctions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int item_iditem { get; set; }
        public int account_idAccount { get; set; }
        public string content { get; set; }
        public Nullable<short> score { get; set; }
    
        public virtual account account { get; set; }
        public virtual item item { get; set; }
    }
}
