//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auctions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public item()
        {
            this.favorite = new HashSet<favorite>();
            this.buy = new HashSet<buy>();
            this.comment = new HashSet<comment>();
            this.sell = new HashSet<sell>();
        }
    
        public int iditem { get; set; }
        public string name { get; set; }
        public string minprice { get; set; }
        public string price { get; set; }
        public int category_idcategory { get; set; }
        public sbyte buy_now { get; set; }
        public string image { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<favorite> favorite { get; set; }
        public virtual ICollection<buy> buy { get; set; }
        public virtual ICollection<comment> comment { get; set; }
        public virtual ICollection<sell> sell { get; set; }
    }
}
