//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auctions.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class auctionsEntities : DbContext
    {
        public auctionsEntities()
            : base("name=auctionsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<account> account { get; set; }
        public DbSet<category> category { get; set; }
        public DbSet<favorite> favorite { get; set; }
        public DbSet<item> item { get; set; }
        public DbSet<role> role { get; set; }
        public DbSet<ban> ban { get; set; }
        public DbSet<buy> buy { get; set; }
        public DbSet<comment> comment { get; set; }
        public DbSet<sell> sell { get; set; }
    }
}
