//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod Ÿród³owy zosta³ wygenerowany na podstawie szablonu.
//
//    Rêczne modyfikacje tego pliku mog¹ spowodowaæ nieoczekiwane zachowanie aplikacji.
//    Rêczne modyfikacje tego pliku zostan¹ zast¹pione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auctions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public role()
        {
            this.account = new HashSet<account>();
        }
    
        public int idrole { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<account> account { get; set; }
    }
}
